class RandomContent {
    $Treasures
    $PanicPlots
    $SideQuests
    $NameVariants
    $Weather
    $Inn
    $Vendors
    $Lore
    $PanicLocations
    $Allies
    $Neutrals
    $Villains
    $MonsterKits
    $ExtraMonsterKits
    $NPCKits
    $Prophecies
    $Omens
    $Graffiti
    $SecretDoors
    $Castles
    $LegendaryItems
    $Pockets
    $Tomes
    $Traps
    $GiantBags
    $Descriptions
}